services:
  rtc-audio-client:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_OFFER_URL=${VITE_OFFER_URL}
    env_file:
      - .env
    ports:
      - 81:80
    networks:
      - agent-network

networks:
  agent-network:
    external: true